### ISSUE TITLE
II stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/VkClient#1]
- `std::cerr` [здесь](https://github.com/lisa-bella97/VkClient/blob/master/sources/client.cpp#L33), [здесь](https://github.com/lisa-bella97/VkClient/blob/master/sources/client.cpp#L70) и [здесь](https://github.com/lisa-bella97/VkClient/blob/master/sources/client.cpp#L103) больше подойдет.

**Comment by lisa-bella97** [comment]
Closed this in d5652ba
