### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/VkClient#2]
@lisa-bella97 

- отсутствует проверка корректного состояния стандартного потока ввода. [здесь](https://github.com/lisa-bella97/VkClient/blob/6e24a38793e5eccab45b05dc3d084e8c900109a1/examples/main.cpp#L10) и [здесь](https://github.com/lisa-bella97/VkClient/blob/6e24a38793e5eccab45b05dc3d084e8c900109a1/examples/main.cpp#L16)

**Comment by lisa-bella97** [comment]
closed this in a765b24
